name: Generate SoH Archive

on:
  workflow_dispatch:
  push:
    branches: [ "2.0-no-ootrs" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate SoH archive
      run: |
        cd data
        wget https://www.dropbox.com/scl/fi/yv73fcy3tyhau00prdfrm/SequenceOTRizer-0.2-Linux.tar.gz?rlkey=yy5x32q0z54metnb935z1z3td&dl=1 -O SequenceOTRizer-0.2-Linux.tar.gz
        tar -xzvf SequenceOTRizer-0.2-Linux.tar.gz
        ./SequenceOTRizer --seq-path Music --otr-name daruniasjoy

    - name: Upload generated daruniasjoy.otr
      uses: actions/upload-artifact@v3
      with:
        name: daruniasjoy.otr
        path: data/mods
